language: haskell

env:
  matrix:
    - HPVER=2012.4.0.0
    - HPVER=2013.2.0.0
    - GHCVER=7.4.2
    - GHCVER=7.6.3
    - GHCVER=head
  global:
    - CABALVER=1.18
    - secure: "n2kMXZFnvArz8nFjzTGqoOiD+TA5sdKz75GnfgBeVGFxMy7uHgdCvmSAMG2xZr57fdZs+qaJLw7e4Ra0XZzFCo0Taz3+b0O4z1kmNizX3CJ0nVEQYhosGwRqBGrLWRQ7t052b52qh7XYGwpaV751A6+VQv4zo5hxUuVmtuJWjck="

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
  - echo $SECURE
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install:
  - ./travis/scripts/install.sh

script:
  - ./travis/scripts/script.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#diagrams"
    skip_join: true
    template:
      - "\x0313diagrams-core\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
