language: haskell

env:
  matrix:
    - HPVER=2012.4.0.0
    - HPVER=2013.2.0.0
    - GHCVER=7.4.2
    - GHCVER=7.6.3
    - GHCVER=head
  global:
    - CABALVER=1.18

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - ./travis/scripts/before_install.sh

install:
  - echo $NUM_CPU
  - cabal-1.18 update
  - cabal-1.18 install 'haddock >= 2.13' -j$NUM_CPU
  - cabal-1.18 install --enable-tests --enable-benchmarks --only-dependencies -j$NUM_CPU

script:
  - cabal-1.18 configure --enable-tests --enable-benchmarks -v2
  - cabal-1.18 build --ghc-options='-Wall -Werror'
  - cabal-1.18 test
  - cabal-1.18 haddock
  - cabal-1.18 check
  - cabal-1.18 sdist

notifications:
  email: false

#  irc:
#    channels:
#      - "irc.freenode.org#diagrams"
#    skip_join: true
#    template:
#      - "\x0313diagrams-core\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
