language: haskell
sudo: false

matrix:
  include:
    - env: HPVER=2013.2.0.0 CABALVER=1.18
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.6.3], sources: [hvr-ghc]}}
    - env: HPVER=2014.2.0.0 CABALVER=1.18
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.6.3 CABALVER=1.18
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.6.3], sources: [hvr-ghc]}}
    - env: GHCVER=7.8.4 CABALVER=1.18
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.3 CABALVER=1.22
      addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.3], sources: [hvr-ghc]}}
    - env: GHCVER=head CABALVER=head
      addons: {apt: {packages: [cabal-install-head, ghc-head], sources: [hvr-ghc]}}
  allow_failures:
    - env: GHCVER=head CABALVER=head

global:
    - HEAD_DEPS="monoid-extras dual-tree"

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/git_deps.sh

install:
  - ./travis/scripts/install.sh

script:
  - ./travis/scripts/script.sh

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#diagrams"
    skip_join: true
    template:
      - "\x0313diagrams-core\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
