language: haskell

before_install:
  - git clone --quiet -b internal-d git://github.com/diagrams/dual-tree.git diagrams/dual-tree
  - cd diagrams
  - cabal install dual-tree/
  - cd ..
script:
  - cabal configure --enable-tests && cabal build --ghc-options='-Wall -Werror' && cabal test && cabal haddock
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#diagrams"
    skip_join: true
    template:
      - "\x0313diagrams-core\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
